export const SENDTASK = "SEND_TASK";
export const SEARCHTASKERS = "SEARCHTASKERS";
export const CLEARSEARCHTASKERS = "CLEARSEARCHTASKERS";
export const TASKNAME = "TASKNAME";
export const CONFIRMTASKS = "CONFIRMTASKS";
export const CLEARCONFIRMTASKS = "CLEARCONFIRMTASKS";
export const CLEARTASKDETAILS = "CLEARTASKDETAILS";

export const USERREGISTER = "USERREGISTER";
export const BECOME_TASKER = "BECOME_TASKER";
export const TASKER_DETAIL = "TASKER_DETAIL";
export const GETTASKS = "GETTASKS";
export const EDITTASKERDETAILS = "EDITTASKERDETAILS";
export const USERLOGIN = "USERLOGIN";
export const LOGINSTATUS = "LOGINSTATUS";
export const SAVEEDIT = "SAVEEDIT";
export const LOGOUT = "LOGOUT";
