export const SENDTASK = "SEND_TASK";
export const SEARCHTASKERS = "SEARCHTASKERS";
export const CLEARSEARCHTASKERS = "CLEARSEARCHTASKERS";
export const TASKNAME = "TASKNAME";
export const CONFIRMTASKS = "CONFIRMTASKS";
export const CLEARCONFIRMTASKS = "CLEARCONFIRMTASKS";
export const CLEARTASKDETAILS = "CLEARTASKDETAILS";

export const USERREGISTER = "USERREGISTER";
